### PR TITLE
Fix compilation error introduced with #201, for Intel-Release and AOCC builds

### PR DESCRIPTION
**Pull request by wdeconinck**
#### The issue

Compilation error with Intel (LLVM) compiler in Release build:
```
eckit/maths/FloatingPointExceptions.cc:26:14: error: '#pragma STDC FENV_ACCESS ON' is illegal when precise is disabled
  | #pragma STDC FENV_ACCESS ON
  |              ^
```
#### Reproduce on the ECMWF HPC:
```
module load pil
module load cmake/new
mkdir build
cmake .. -DCMAKE_BUILD_TYPE=Release
make
```
#### Possible fixes
- Remove the pragma; it seems to work, at least for this setup.
- Add compilation flag `-fp-model precise` for the file `eckit/maths/FloatingPointExceptions.cc` for the Intel compiler

I have chosen to add the compilation flag.

### CODE REVIEW

**Comment by wdeconinck** [comment]
After some further information by @shahramn ,  it seems the pragma is further causing internal compiler error with AMD's aocc compiler.
This can be reproduced on our HPC with:
```
module load prgenv/amd
module load aocc/4.0.0
module load cmake/new
mkdir build
cmake .. -DCMAKE_BUILD_TYPE=Release
make
```
<details>

<summary>Output</summary>

```
[310/720] Building CXX object src/eckit/maths/CMakeFiles/eckit_maths.dir/FloatingPointExceptions.cc.o
FAILED: src/eckit/maths/CMakeFiles/eckit_maths.dir/FloatingPointExceptions.cc.o
/usr/local/apps/aocc/4.0.0/bin/clang++ -Deckit_maths_EXPORTS -I/etc/ecmwf/ssd/ssd1/ecinteractive/nawd-ecinteractive/eckit-fpe/build-aocc/src -I/etc/ecmwf/ssd/ssd1/ecinteractive/nawd-ecinteractive/eckit-fpe/eckit/src -pipe -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-sign-compare -O3 -DNDEBUG -std=gnu++17 -fPIC -MD -MT src/eckit/maths/CMakeFiles/eckit_maths.dir/FloatingPointExceptions.cc.o -MF src/eckit/maths/CMakeFiles/eckit_maths.dir/FloatingPointExceptions.cc.o.d -o src/eckit/maths/CMakeFiles/eckit_maths.dir/FloatingPointExceptions.cc.o -c /etc/ecmwf/ssd/ssd1/ecinteractive/nawd-ecinteractive/eckit-fpe/eckit/src/eckit/maths/FloatingPointExceptions.cc
clang++: /home/amd/JENKINS/workspace/AOCC_4_0_0_INTERIM/llvm-project/clang/lib/CodeGen/CodeGenFunction.cpp:163: void clang::CodeGen::CodeGenFunction::CGFPOptionsRAII::ConstructorHelper(clang::FPOptions): Assertion `(CGF.CurFuncDecl == nullptr || CGF.Builder.getIsFPConstrained() || isa<CXXConstructorDecl>(CGF.CurFuncDecl) || isa<CXXDestructorDecl>(CGF.CurFuncDecl) || (NewExceptionBehavior == llvm::fp::ebIgnore && NewRoundingBehavior == llvm::RoundingMode::NearestTiesToEven)) && "FPConstrained should be enabled on entire function"' failed.
PLEASE submit a bug report to the technical support section of https://developer.amd.com/amd-aocc and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /usr/local/apps/aocc/4.0.0/bin/clang++ -Deckit_maths_EXPORTS -I/etc/ecmwf/ssd/ssd1/ecinteractive/nawd-ecinteractive/eckit-fpe/build-aocc/src -I/etc/ecmwf/ssd/ssd1/ecinteractive/nawd-ecinteractive/eckit-fpe/eckit/src -pipe -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-sign-compare -O3 -DNDEBUG -std=gnu++17 -fPIC -MD -MT src/eckit/maths/CMakeFiles/eckit_maths.dir/FloatingPointExceptions.cc.o -MF src/eckit/maths/CMakeFiles/eckit_maths.dir/FloatingPointExceptions.cc.o.d -o src/eckit/maths/CMakeFiles/eckit_maths.dir/FloatingPointExceptions.cc.o -c /etc/ecmwf/ssd/ssd1/ecinteractive/nawd-ecinteractive/eckit-fpe/eckit/src/eckit/maths/FloatingPointExceptions.cc
1.	<eof> parser at end of file
2.	Per-file LLVM IR generation
3.	/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/basic_string.h:272:9: Generating code for declaration 'std::basic_string<char>::_M_construct'
 #0 0x0000146d72adcd9f PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x0000146d72adadec llvm::sys::CleanupOnSignal(unsigned long) (/usr/local/apps/aocc/4.0.0/bin/../lib/libLLVMSupport.so.14+0x1d2dec)
 #2 0x0000146d729c9ca8 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x0000146d71bda990 __restore_rt (/lib64/libpthread.so.0+0x12990)
 #4 0x0000146d6eb8852f raise (/lib64/libc.so.6+0x4e52f)
 #5 0x0000146d6eb5be65 abort (/lib64/libc.so.6+0x21e65)
 #6 0x0000146d6eb5bd39 _nl_load_domain.cold.0 (/lib64/libc.so.6+0x21d39)
 #7 0x0000146d6eb80e86 (/lib64/libc.so.6+0x46e86)
 #8 0x0000146d70c3c57e clang::CodeGen::CodeGenFunction::CGFPOptionsRAII::ConstructorHelper(clang::FPOptions) (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x46357e)
 #9 0x0000146d70a5f5a3 clang::CodeGen::CodeGenFunction::EvaluateExprAsBool(clang::Expr const*) (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x2865a3)
#10 0x0000146d70c41f11 clang::CodeGen::CodeGenFunction::EmitBranchOnBoolExpr(clang::Expr const*, llvm::BasicBlock*, llvm::BasicBlock*, unsigned long, clang::Stmt::Likelihood) (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x468f11)
#11 0x0000146d70c42318 clang::CodeGen::CodeGenFunction::EmitBranchOnBoolExpr(clang::Expr const*, llvm::BasicBlock*, llvm::BasicBlock*, unsigned long, clang::Stmt::Likelihood) (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x469318)
#12 0x0000146d70be0cc4 clang::CodeGen::CodeGenFunction::EmitIfStmt(clang::IfStmt const&) (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x407cc4)
#13 0x0000146d70bdab3e clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x401b3e)
#14 0x0000146d70be120c clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x40820c)
#15 0x0000146d70c3d4a3 clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::Stmt const*) (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x4644a3)
#16 0x0000146d70c4cc64 clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x473c64)
#17 0x0000146d70c93bd9 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x4babd9)
#18 0x0000146d70c8ffb5 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x4b6fb5)
#19 0x0000146d70c97b7c clang::CodeGen::CodeGenModule::EmitDeferred() (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x4beb7c)
#20 0x0000146d70c97ac8 clang::CodeGen::CodeGenModule::EmitDeferred() (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x4beac8)
#21 0x0000146d70c97ac8 clang::CodeGen::CodeGenModule::EmitDeferred() (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x4beac8)
#22 0x0000146d70c97ac8 clang::CodeGen::CodeGenModule::EmitDeferred() (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x4beac8)
#23 0x0000146d70c97ac8 clang::CodeGen::CodeGenModule::EmitDeferred() (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x4beac8)
#24 0x0000146d70c97ac8 clang::CodeGen::CodeGenModule::EmitDeferred() (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x4beac8)
#25 0x0000146d70c97ac8 clang::CodeGen::CodeGenModule::EmitDeferred() (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x4beac8)
#26 0x0000146d70c97ac8 clang::CodeGen::CodeGenModule::EmitDeferred() (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x4beac8)
#27 0x0000146d70c9a439 clang::CodeGen::CodeGenModule::Release() (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x4c1439)
#28 0x0000146d70d140ea (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) ModuleBuilder.cpp:0:0
#29 0x0000146d70c39c0d clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x460c0d)
#30 0x0000146d688c14e9 clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/apps/aocc/4.0.0/bin/../lib/../lib/libclangParse.so.14+0x334e9)
#31 0x0000146d70c38490 clang::CodeGenAction::ExecuteAction() (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangCodeGen.so.14+0x45f490)
#32 0x0000146d6ffe2af9 clang::FrontendAction::Execute() (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangFrontend.so.14+0x138af9)
#33 0x0000146d6ff584e1 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangFrontend.so.14+0xae4e1)
#34 0x0000146d6fca7043 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangFrontendTool.so.14+0x4043)
#35 0x0000000000415482 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/local/apps/aocc/4.0.0/bin/clang+++0x415482)
#36 0x0000000000410cf7 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#37 0x0000146d703c5035 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::string*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#38 0x0000146d729c9e12 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/usr/local/apps/aocc/4.0.0/bin/../lib/libLLVMSupport.so.14+0xc1e12)
#39 0x0000146d703c59d6 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::string*, bool*) const (.part.201) Job.cpp:0:0
#40 0x0000146d70390168 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangDriver.so.14+0x7b168)
#41 0x0000146d70390c0e clang::driver::Compilation::ExecuteIndividualJob(clang::driver::Command const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangDriver.so.14+0x7bc0e)
#42 0x0000146d703962b2 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangDriver.so.14+0x812b2)
#43 0x0000146d7039fc31 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/usr/local/apps/aocc/4.0.0/bin/../lib/libclangDriver.so.14+0x8ac31)
#44 0x000000000040ebe7 main (/usr/local/apps/aocc/4.0.0/bin/clang+++0x40ebe7)
#45 0x0000146d6eb747e5 __libc_start_main (/lib64/libc.so.6+0x3a7e5)
#46 0x000000000041086e _start (/usr/local/apps/aocc/4.0.0/bin/clang+++0x41086e)
clang-14: error: clang frontend command failed with exit code 134 (use -v to see invocation)
AMD clang version 14.0.6 (CLANG: AOCC_4.0.0-Build#434 2022_10_28) (based on LLVM Mirror.Version.14.0.6)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/apps/aocc/4.0.0/bin
clang-14: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-14: note: diagnostic msg: /etc/ecmwf/ssd/ssd1/ecinteractive/nawd-ecinteractive/tmpdirs/nawd.38849731/FloatingPointExceptions-c41466.cpp
clang-14: note: diagnostic msg: /etc/ecmwf/ssd/ssd1/ecinteractive/nawd-ecinteractive/tmpdirs/nawd.38849731/FloatingPointExceptions-c41466.sh
clang-14: note: diagnostic msg:

********************
```
</details>

**Comment by wdeconinck** [comment]
@Ozaq , @pmaciel , ready for your approval ;-)

**Review by Ozaq — APPROVED** [review]
Approved under the condition that the warning message gets extended to mention that the AOC compiler is the actual problem and not necessarily clang.

**Comment by wdeconinck** [comment]
Note that it may still be possible that clang version < 17 also does not support this, irrespective from aocc. We simply don't have an old clang lying around to verify this at the moment.
